# 供热收费系统语义建模 - SuperSonic元数据导入SQL
# UTF-8编码执行

$connStr = "postgresql://postgres:Huilian1234@192.168.1.7:54321/postgres"

# 主题域
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "SET search_path TO heating_analytics;"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_domain (name, biz_name, parent_id, status, created_at, created_by, updated_at, updated_by, entity) VALUES ('供热收费系统', 'heating_charge', 0, 1, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '供热收费核心业务域');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_domain (name, biz_name, parent_id, status, created_at, created_by, updated_at, updated_by, entity) VALUES ('用户域', 'customer', 1, 1, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '热用户管理');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_domain (name, biz_name, parent_id, status, created_at, created_by, updated_at, updated_by, entity) VALUES ('计费域', 'billing', 1, 1, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '费用计算与结算');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_domain (name, biz_name, parent_id, status, created_at, created_by, updated_at, updated_by, entity) VALUES ('收费域', 'collection', 1, 1, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '实收费用管理');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_domain (name, biz_name, parent_id, status, created_at, created_by, updated_at, updated_by, entity) VALUES ('运营域', 'operation', 1, 1, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '业务运营分析');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_domain (name, biz_name, parent_id, status, created_at, created_by, updated_at, updated_by, entity) VALUES ('质量域', 'quality', 1, 1, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', '数据质量监控');"

# 数据模型
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('用户维度模型', 'sf_dim_customer', 2, '用户信息', 1, '热用户基本信息维度', 1, '{\"tables\": [{\"table\": \"sf_dim_customer\", \"alias\": \"c\", \"schema\": \"heating_analytics\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('组织维度模型', 'sf_dim_org', 2, '组织架构', 1, '组织架构维度', 1, '{\"tables\": [{\"table\": \"sf_dim_org\", \"alias\": \"o\", \"schema\": \"heating_analytics\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('面积维度模型', 'sf_dim_area', 2, '供热面积', 1, '供热面积维度', 1, '{\"tables\": [{\"table\": \"sf_dim_area\", \"alias\": \"a\", \"schema\": \"heating_analytics\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('时间维度模型', 'sf_dim_time', 2, '时间维度', 1, '时间维度', 1, '{\"tables\": [{\"table\": \"sf_dim_time\", \"alias\": \"t\", \"schema\": \"heating_analytics\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('收费结算事实模型', 'sf_rpt_charge', 3, '收费结算', 1, '收费结算核心事实表', 1, '{\"tables\": [{\"table\": \"sf_rpt_charge\", \"alias\": \"m\", \"schema\": \"heating_analytics\"}, {\"table\": \"sf_dim_customer\", \"alias\": \"c\", \"schema\": \"heating_analytics\"}], \"joins\": [{\"left\": \"m.customer_id\", \"right\": \"c.customer_id\", \"type\": \"LEFT JOIN\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('收费明细事实模型', 'sf_rpt_payment', 4, '收费明细', 1, '收费明细事实表', 1, '{\"tables\": [{\"table\": \"sf_rpt_payment\", \"alias\": \"p\", \"schema\": \"heating_analytics\"}, {\"table\": \"sf_dim_customer\", \"alias\": \"c\", \"schema\": \"heating_analytics\"}], \"joins\": [{\"left\": \"p.customer_id\", \"right\": \"c.customer_id\", \"type\": \"LEFT JOIN\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('停供复供事实模型', 'sf_fact_stop_restart', 5, '停供复供', 1, '停供复供业务事实表', 1, '{\"tables\": [{\"table\": \"sf_fact_stop_restart\", \"alias\": \"sr\", \"schema\": \"heating_analytics\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"
& "D:\Program Files\pgAdmin 4\runtime\psql.exe" $connStr -c "INSERT INTO s2_model (name, biz_name, domain_id, alias, status, description, database_id, model_detail, created_at, created_by, updated_at, updated_by, source_type) VALUES ('采暖期收费汇总模型', 'sf_rpt_cnq_charge', 5, '采暖期汇总', 1, '采暖期收费汇总表', 1, '{\"tables\": [{\"table\": \"sf_rpt_cnq_charge\", \"alias\": \"sc\", \"schema\": \"heating_analytics\"}]}', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin', 'TABLE');"

Write-Host "数据导入完成"
