-- ----------------------------
-- Table structure for customer
-- ----------------------------
DROP TABLE IF EXISTS `customer`;
CREATE TABLE `customer`  (
  `id` bigint(0) NOT NULL,
  `code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户编码',
  `yhkh` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户卡号',
  `name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户名称',
  `id_number` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '身份证号',
  `tel_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '座机号',
  `mob_no` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '手机号',
  `ry` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '热源',
  `jz` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '机组',
  `one` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '一级-地区等级名称',
  `two` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '二级-地区等级名称',
  `three` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '三级-地区等级名称',
  `address_prefix` varchar(35) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '地址前缀',
  `unit` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '单元',
  `floor` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '楼层',
  `room` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '房间',
  `mp` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '门牌号',
  `address` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '地址',
  `yhlx` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户类型：居民/单位',
  `rwrq` date NULL DEFAULT NULL COMMENT '入网日期',
  `rwht_bh` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '入网合同编号',
  `kzfs` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '控制方式： 分户 未分户',
  `created_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `updated_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
  `bz` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '备注',
  `zf` tinyint(1) NOT NULL COMMENT '是否作废： 0-正常 1-作废',
  `kz_hmd` tinyint(1) NOT NULL DEFAULT 0 COMMENT '用户控制-是否黑名单： 0-否 1-是',
  `kz_hmd_reason` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户控制-是否黑名单-原因',
  `kz_sf` tinyint(1) NOT NULL DEFAULT 1 COMMENT '用户控制-是否允许收费： 0-否 1-是',
  `kz_sf_reason` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户控制-是否允许收费-原因',
  `kz_yhsf` tinyint(1) NOT NULL DEFAULT 1 COMMENT '用户控制-是否允许银行收费： 0-否 1-是',
  `kz_jcsh` tinyint(1) NOT NULL DEFAULT 0 COMMENT '用户控制-稽查锁户： 0-否 1-是',
  `kz_jcsh_reason` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户控制-稽查锁户-原因',
  `czbh` bigint(0) NOT NULL COMMENT '操作编号',
  `glh` bigint(0) NULL DEFAULT NULL COMMENT '关联号',
  `fmzt` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '阀门状态',
  `fmzt_ing` int(0) NULL DEFAULT NULL COMMENT '阀门执行状态',
  `fmzt_res` tinyint(1) NULL DEFAULT NULL COMMENT '阀门处理状态',
  `xzcnq` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '新增采暖期',
  `temperature` decimal(10, 3) NULL DEFAULT NULL COMMENT '室内温度',
  `rlz_id` bigint(0) NULL DEFAULT NULL COMMENT '热力站主键',
  `zdfq_id` bigint(0) NULL DEFAULT NULL COMMENT '站点分区主键',
  `zdfq_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '站点分区名称',
  `hrq_zt` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '换热器状态',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `code`(`code`) USING BTREE,
  INDEX `org`(`one`, `two`, `three`) USING BTREE,
  INDEX `zf`(`zf`) USING BTREE,
  INDEX `name`(`name`, `address`, `mob_no`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '用户信息表' ROW_FORMAT = Dynamic;

